@startuml
title サービス情報入力時の処理

actor Client <<user>>
participant View
control Task
collections Reducer
database State
participant API

group ユーザの情報入力
    Client -> View: フォームに値を入力
    View -> Reducer: Action\n任意のredux-formのAction
    Reducer -> State: Reducer\nフォーム要素の値更新
    hnote over State #fffacd: form.registData
    State -> View: フォーム要素の値更新反映
    View -> Client: フォームに値が反映される
end

group 入力された情報の確認画面への遷移
    Client -> View: 「登録する」ボタンを押す
    View -> Task: onSubmit\nactions@postRegistData(params)\nPOST_REGIST_DATA,params
    activate Task #ef857d
    hnote over Task #a3d6cc : hundleRequestPostRegistData
    Task -> View: saga@put\nstartSubmit
    activate View #ffe9a9
    hnote over View #ead7a4 :『登録中』のポップアップ表示
    Task -> API: saga@call\nPOST /regist\nbody: JSON.stringify(params)
    alt Create 201
        API -> Task: response status 201 craeted
        Task -> View: saga@put\nstopSubmit
        deactivate View
        Task -> View : saga@put\nreset
        hnote over View #ead7a4 : form要素のリセット
        Task -> View: next-routes@pushRoutes\nservice/list
        deactivate Task
        hnote over View #ead7a4 : サービス一覧へ遷移
        View -> Client: GET 200 service/list
    else WIP faild 4XX or 5XX
        API -> Task: error
        Task -> View: saga@put\nstopSubmit
        Task -> View: saga@put\nsetSubmitFailed
        View -> Client: 登録エラーのポップアップ表示
    end
end

@enduml